### PR TITLE
Teach cmsBuild to make use of build stats to optimize the build time

### PR DESCRIPTION
**Pull request by smuzaffar**
Based on #172.
These changes allows cmsBuild to make use of build stats from previous runs and optimize the parallel build of multiple packages ( as long as the cpu and memory consumption of packages is under max cpu/memory limit). The format of build stats json file should be
```
{
  # Some default values for unknown packages
  "defaults": {
    "cpu": (cpu%_single_process_jobs, cpu%_multi_process_jobs),
    "rss": (rss_in_bytes_single_process_jobs, rss_in_bytes_multi_process_jobs),
    "time": (build_time_single_process_job, build_time_for_multi_process_jobs)
  },
  # maximum resources available
  "resources":{"cpu": max_cpu%_available, "rss": max_memory_available},
  # stats of packages
  "packages": { "name": {"cpu": value, "rss": value, "time": value}},
  # some defaults for known packages, first item is name of package to match and 2nd item is the index in the data["defaults"] for a resource
  "known": [
    (package_regexp, index_in_default), 
    ]
  }
```
e.g.
```
{
  "defaults": {
    "cpu": (50, total_cpu%/4),
    "rss": (total_memory/total_cpu, total_memory/4),
    "time": (1, 300)
  },
  "resources":{"cpu": total_cpu%, "rss": total_memory},
  "packages": {
    "root": {"cpu": 800, "rss": 8GB, "time": 3600},
    "boost": {"cpu": 640, "rss": 4GB, "time": 1800}
  },
  "known": [
    ("^.+-toolfile$", 0), 
    ("^data-.+$", 0),
    ("^.+$", 1)
    ]
  }
```

here are some build results on a 16 core build machine
1- Old pkgtools with `--builders 1 -j 16` : build time 12h15 for all externals (except gcc)

old-1builder

2- Old pkgtools with  `--builders 3 -j 16` : build time 8h10 for all externals (except gcc)

old-3builders

3- New pkgtools with  `--builders 16 -j 16 --esstats stats-from-step1.json`  : build time 5h50

new

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by mrodozov** [comment]
it also reminds me we have to enable the stats for Arm because we've disabled them to check if the monitoring causes failure which I think it doesn't

**Comment by mrodozov** [comment]
I have to try this my attempts were finishing with ~10 hours at best and LLVM and ROOT competing for CPU slowing down ~1hour everything, and this is like ... 25% improvement 😃 The best improvement I got was 10 minutes in 10 hours 😃

**Comment by smuzaffar** [comment]
@mrodozov , see https://github.com/cms-sw/cmsdist/pull/6738/files . The `-l $(nproc)` causes these externals to never overload the system . That is one of the reasons why we see very low `cpu_90` as compare to `cpu_max` . With the change of https://github.com/cms-sw/cmsdist/pull/6738 , we should get better `cpu_90` values. 

Note that I first locally run existing `cmsBuild` with https://github.com/cms-sw/cmsdist/pull/6738 changes to get correct stats and then fed those stats to new `cmsBuild` . I think thatis the reason why I see a lot build time gain

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#6735

**Comment by smuzaffar** [comment]
please test

**Pull request merged**
