### PR TITLE
Add option to store package deps - pkgtools V33

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
test parameters:
- architecture = cc8_amd64_gcc8

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
@mrodozov , one thing whuch I did not try is the check if json module is available via system python :-)
Van you please try to run V00-32-XX on slc6?

**Comment by mrodozov** [comment]
It's running, I tried it on lxplus and with slc6 singularity (system python 2.6.6 using import)
and also
`./pkgtools/cmsBuild -i build_cmssw/ -c cmsdist --repository cms.week1 -a slc6_amd64_gcc480 -j 16 --pretend --ldps build fakesystem`
using cmsdist branch IB/CMSSW_7_0_X/slc6_amd64_gcc480
it should be, json is one of the oldest modules there is

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
